# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "smtp-server" do |cfg|
    cfg.vm.box = "fedora/27-cloud-base"
    cfg.vm.network "private_network", ip: "172.25.11.5"
    cfg.vm.provision "shell", path: "setup-client.sh"
    cfg.vm.provision "shell", path: "setup-imap.sh"
    cfg.vm.provision "shell", path: "setup-smtp.sh"
    cfg.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "noauth-client" do |cfg|
    cfg.vm.box = "fedora/27-cloud-base"
    cfg.vm.network "private_network", ip: "172.25.11.10"
    cfg.vm.provision "shell", path: "setup-client.sh"
    cfg.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "auth-client" do |cfg|
    cfg.vm.box = "fedora/27-cloud-base"
    cfg.vm.network "private_network", ip: "172.25.11.42"
    cfg.vm.provision "shell", path: "setup-client.sh"
    cfg.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "sandbox" do |cfg|
    cfg.vm.box = "fedora/27-cloud-base"
    cfg.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end
end
