# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dovecot" do |cfg|
    cfg.vm.box = "fedora/27-cloud-base"
    cfg.vm.provision "shell", path: "setup-client.sh"
    cfg.vm.provision "shell", path: "mail.sh"
    cfg.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end
end
